#!/bin/bash
#Runs a custom menu of all the sell scripts saved in $HOME/.dwm/custom_scripts

SCRIPTS_PATH="$HOME/.dwm/custom_scripts/"
mkdir -p "$SCRIPTS_PATH"
cd "$SCRIPTS_PATH"

if [ `find ./ -type f | wc -l` == "0" ]; then #empty folder
	exit;
fi

find ./ -type f | cut -d '/' -f 2- | dmenu | xargs bash
